package com.yy.ent.tvbar.dao.mapper;

import com.yy.ent.tvbar.common.model.domain.EventGroup;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("eventid") Integer eventid, @Param("groupid") Integer groupid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_group
     *
     * @mbggenerated
     */
    int insert(EventGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_group
     *
     * @mbggenerated
     */
    List<EventGroup> selectAll();
}