package com.yy.ent.tvbar.dao.mapper;

import com.yy.ent.tvbar.common.model.domain.Evidence;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EvidenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("evidenceid") Integer evidenceid, @Param("replyid") Integer replyid, @Param("creatorid") String creatorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbggenerated
     */
    int insert(Evidence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbggenerated
     */
    Evidence selectByPrimaryKey(@Param("evidenceid") Integer evidenceid, @Param("replyid") Integer replyid, @Param("creatorid") String creatorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbggenerated
     */
    List<Evidence> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Evidence record);
}