package com.yy.ent.tvbar.dao.mapper;

import com.yy.ent.tvbar.common.model.domain.HistoryGroup;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HistoryGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("userid") String userid, @Param("groupid") Integer groupid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_group
     *
     * @mbggenerated
     */
    int insert(HistoryGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_group
     *
     * @mbggenerated
     */
    HistoryGroup selectByPrimaryKey(@Param("userid") String userid, @Param("groupid") Integer groupid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_group
     *
     * @mbggenerated
     */
    List<HistoryGroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HistoryGroup record);
}