package com.yy.ent.tvbar.dao.mapper;

import com.yy.ent.tvbar.common.model.domain.ReplyHotReq;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReplyHotReqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_hot_req
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("replyid") Integer replyid, @Param("userid") String userid, @Param("type") Integer type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_hot_req
     *
     * @mbggenerated
     */
    int insert(ReplyHotReq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_hot_req
     *
     * @mbggenerated
     */
    ReplyHotReq selectByPrimaryKey(@Param("replyid") Integer replyid, @Param("userid") String userid, @Param("type") Integer type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_hot_req
     *
     * @mbggenerated
     */
    List<ReplyHotReq> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_hot_req
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReplyHotReq record);
}