package com.yy.ent.tvbar.dao.mapper;

import com.yy.ent.tvbar.common.model.domain.Router;
import java.util.List;

public interface RouterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table router
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table router
     *
     * @mbggenerated
     */
    int insert(Router record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table router
     *
     * @mbggenerated
     */
    Router selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table router
     *
     * @mbggenerated
     */
    List<Router> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table router
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Router record);
}