package com.yy.ent.tvbar.dao.mapper;

import com.yy.ent.tvbar.common.model.domain.Text;
import java.util.List;

public interface TextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text
     *
     * @mbggenerated
     */
    int insert(Text record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text
     *
     * @mbggenerated
     */
    Text selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text
     *
     * @mbggenerated
     */
    List<Text> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Text record);
}