package com.yy.ent.tvbar.dao.mapper;

import com.yy.ent.tvbar.common.model.domain.Voice;
import java.util.List;

public interface VoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice
     *
     * @mbggenerated
     */
    int insert(Voice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice
     *
     * @mbggenerated
     */
    Voice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice
     *
     * @mbggenerated
     */
    List<Voice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Voice record);
}