package com.yy.ent.tvbar.common.model.domain;

public class Event {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.eventId
     *
     * @mbggenerated
     */
    private Integer eventid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.zhiType
     *
     * @mbggenerated
     */
    private Byte zhitype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.eventId
     *
     * @return the value of event.eventId
     *
     * @mbggenerated
     */
    public Integer getEventid() {
        return eventid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.eventId
     *
     * @param eventid the value for event.eventId
     *
     * @mbggenerated
     */
    public void setEventid(Integer eventid) {
        this.eventid = eventid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.zhiType
     *
     * @return the value of event.zhiType
     *
     * @mbggenerated
     */
    public Byte getZhitype() {
        return zhitype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.zhiType
     *
     * @param zhitype the value for event.zhiType
     *
     * @mbggenerated
     */
    public void setZhitype(Byte zhitype) {
        this.zhitype = zhitype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.description
     *
     * @return the value of event.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.description
     *
     * @param description the value for event.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Event other = (Event) that;
        return (this.getEventid() == null ? other.getEventid() == null : this.getEventid().equals(other.getEventid()))
            && (this.getZhitype() == null ? other.getZhitype() == null : this.getZhitype().equals(other.getZhitype()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEventid() == null) ? 0 : getEventid().hashCode());
        result = prime * result + ((getZhitype() == null) ? 0 : getZhitype().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", eventid=").append(eventid);
        sb.append(", zhitype=").append(zhitype);
        sb.append(", description=").append(description);
        sb.append("]");
        return sb.toString();
    }
}