package com.yy.ent.tvbar.common.model.domain;

public class EventGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_group.eventId
     *
     * @mbggenerated
     */
    private Integer eventid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_group.groupId
     *
     * @mbggenerated
     */
    private Integer groupid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_group.eventId
     *
     * @return the value of event_group.eventId
     *
     * @mbggenerated
     */
    public Integer getEventid() {
        return eventid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_group.eventId
     *
     * @param eventid the value for event_group.eventId
     *
     * @mbggenerated
     */
    public void setEventid(Integer eventid) {
        this.eventid = eventid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_group.groupId
     *
     * @return the value of event_group.groupId
     *
     * @mbggenerated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_group.groupId
     *
     * @param groupid the value for event_group.groupId
     *
     * @mbggenerated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_group
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EventGroup other = (EventGroup) that;
        return (this.getEventid() == null ? other.getEventid() == null : this.getEventid().equals(other.getEventid()))
            && (this.getGroupid() == null ? other.getGroupid() == null : this.getGroupid().equals(other.getGroupid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_group
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEventid() == null) ? 0 : getEventid().hashCode());
        result = prime * result + ((getGroupid() == null) ? 0 : getGroupid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_group
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", eventid=").append(eventid);
        sb.append(", groupid=").append(groupid);
        sb.append("]");
        return sb.toString();
    }
}