package com.yy.ent.tvbar.common.model.domain;

import java.util.Date;

public class Evidence {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evidence.evidenceId
     *
     * @mbggenerated
     */
    private Integer evidenceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evidence.replyId
     *
     * @mbggenerated
     */
    private Integer replyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evidence.creatorId
     *
     * @mbggenerated
     */
    private String creatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evidence.topicId
     *
     * @mbggenerated
     */
    private Integer topicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evidence.picture
     *
     * @mbggenerated
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evidence.handlePic
     *
     * @mbggenerated
     */
    private String handlepic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evidence.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evidence.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evidence.enable
     *
     * @mbggenerated
     */
    private Byte enable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evidence.evidenceId
     *
     * @return the value of evidence.evidenceId
     *
     * @mbggenerated
     */
    public Integer getEvidenceid() {
        return evidenceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evidence.evidenceId
     *
     * @param evidenceid the value for evidence.evidenceId
     *
     * @mbggenerated
     */
    public void setEvidenceid(Integer evidenceid) {
        this.evidenceid = evidenceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evidence.replyId
     *
     * @return the value of evidence.replyId
     *
     * @mbggenerated
     */
    public Integer getReplyid() {
        return replyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evidence.replyId
     *
     * @param replyid the value for evidence.replyId
     *
     * @mbggenerated
     */
    public void setReplyid(Integer replyid) {
        this.replyid = replyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evidence.creatorId
     *
     * @return the value of evidence.creatorId
     *
     * @mbggenerated
     */
    public String getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evidence.creatorId
     *
     * @param creatorid the value for evidence.creatorId
     *
     * @mbggenerated
     */
    public void setCreatorid(String creatorid) {
        this.creatorid = creatorid == null ? null : creatorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evidence.topicId
     *
     * @return the value of evidence.topicId
     *
     * @mbggenerated
     */
    public Integer getTopicid() {
        return topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evidence.topicId
     *
     * @param topicid the value for evidence.topicId
     *
     * @mbggenerated
     */
    public void setTopicid(Integer topicid) {
        this.topicid = topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evidence.picture
     *
     * @return the value of evidence.picture
     *
     * @mbggenerated
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evidence.picture
     *
     * @param picture the value for evidence.picture
     *
     * @mbggenerated
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evidence.handlePic
     *
     * @return the value of evidence.handlePic
     *
     * @mbggenerated
     */
    public String getHandlepic() {
        return handlepic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evidence.handlePic
     *
     * @param handlepic the value for evidence.handlePic
     *
     * @mbggenerated
     */
    public void setHandlepic(String handlepic) {
        this.handlepic = handlepic == null ? null : handlepic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evidence.description
     *
     * @return the value of evidence.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evidence.description
     *
     * @param description the value for evidence.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evidence.createTime
     *
     * @return the value of evidence.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evidence.createTime
     *
     * @param createtime the value for evidence.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evidence.enable
     *
     * @return the value of evidence.enable
     *
     * @mbggenerated
     */
    public Byte getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evidence.enable
     *
     * @param enable the value for evidence.enable
     *
     * @mbggenerated
     */
    public void setEnable(Byte enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Evidence other = (Evidence) that;
        return (this.getEvidenceid() == null ? other.getEvidenceid() == null : this.getEvidenceid().equals(other.getEvidenceid()))
            && (this.getReplyid() == null ? other.getReplyid() == null : this.getReplyid().equals(other.getReplyid()))
            && (this.getCreatorid() == null ? other.getCreatorid() == null : this.getCreatorid().equals(other.getCreatorid()))
            && (this.getTopicid() == null ? other.getTopicid() == null : this.getTopicid().equals(other.getTopicid()))
            && (this.getPicture() == null ? other.getPicture() == null : this.getPicture().equals(other.getPicture()))
            && (this.getHandlepic() == null ? other.getHandlepic() == null : this.getHandlepic().equals(other.getHandlepic()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getEnable() == null ? other.getEnable() == null : this.getEnable().equals(other.getEnable()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEvidenceid() == null) ? 0 : getEvidenceid().hashCode());
        result = prime * result + ((getReplyid() == null) ? 0 : getReplyid().hashCode());
        result = prime * result + ((getCreatorid() == null) ? 0 : getCreatorid().hashCode());
        result = prime * result + ((getTopicid() == null) ? 0 : getTopicid().hashCode());
        result = prime * result + ((getPicture() == null) ? 0 : getPicture().hashCode());
        result = prime * result + ((getHandlepic() == null) ? 0 : getHandlepic().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getEnable() == null) ? 0 : getEnable().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evidence
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", evidenceid=").append(evidenceid);
        sb.append(", replyid=").append(replyid);
        sb.append(", creatorid=").append(creatorid);
        sb.append(", topicid=").append(topicid);
        sb.append(", picture=").append(picture);
        sb.append(", handlepic=").append(handlepic);
        sb.append(", description=").append(description);
        sb.append(", createtime=").append(createtime);
        sb.append(", enable=").append(enable);
        sb.append("]");
        return sb.toString();
    }
}