package com.yy.ent.tvbar.common.model.domain;

import java.util.Date;

public class Groups {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.groupId
     *
     * @mbggenerated
     */
    private Integer groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.headIconUrl
     *
     * @mbggenerated
     */
    private String headiconurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.creatorId
     *
     * @mbggenerated
     */
    private String creatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.attentionCount
     *
     * @mbggenerated
     */
    private Integer attentioncount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.recommend
     *
     * @mbggenerated
     */
    private Byte recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.enable
     *
     * @mbggenerated
     */
    private Byte enable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.groupId
     *
     * @return the value of groups.groupId
     *
     * @mbggenerated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.groupId
     *
     * @param groupid the value for groups.groupId
     *
     * @mbggenerated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.title
     *
     * @return the value of groups.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.title
     *
     * @param title the value for groups.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.type
     *
     * @return the value of groups.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.type
     *
     * @param type the value for groups.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.description
     *
     * @return the value of groups.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.description
     *
     * @param description the value for groups.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.headIconUrl
     *
     * @return the value of groups.headIconUrl
     *
     * @mbggenerated
     */
    public String getHeadiconurl() {
        return headiconurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.headIconUrl
     *
     * @param headiconurl the value for groups.headIconUrl
     *
     * @mbggenerated
     */
    public void setHeadiconurl(String headiconurl) {
        this.headiconurl = headiconurl == null ? null : headiconurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.creatorId
     *
     * @return the value of groups.creatorId
     *
     * @mbggenerated
     */
    public String getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.creatorId
     *
     * @param creatorid the value for groups.creatorId
     *
     * @mbggenerated
     */
    public void setCreatorid(String creatorid) {
        this.creatorid = creatorid == null ? null : creatorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.createTime
     *
     * @return the value of groups.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.createTime
     *
     * @param createtime the value for groups.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.attentionCount
     *
     * @return the value of groups.attentionCount
     *
     * @mbggenerated
     */
    public Integer getAttentioncount() {
        return attentioncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.attentionCount
     *
     * @param attentioncount the value for groups.attentionCount
     *
     * @mbggenerated
     */
    public void setAttentioncount(Integer attentioncount) {
        this.attentioncount = attentioncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.recommend
     *
     * @return the value of groups.recommend
     *
     * @mbggenerated
     */
    public Byte getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.recommend
     *
     * @param recommend the value for groups.recommend
     *
     * @mbggenerated
     */
    public void setRecommend(Byte recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.enable
     *
     * @return the value of groups.enable
     *
     * @mbggenerated
     */
    public Byte getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.enable
     *
     * @param enable the value for groups.enable
     *
     * @mbggenerated
     */
    public void setEnable(Byte enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Groups other = (Groups) that;
        return (this.getGroupid() == null ? other.getGroupid() == null : this.getGroupid().equals(other.getGroupid()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getHeadiconurl() == null ? other.getHeadiconurl() == null : this.getHeadiconurl().equals(other.getHeadiconurl()))
            && (this.getCreatorid() == null ? other.getCreatorid() == null : this.getCreatorid().equals(other.getCreatorid()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getAttentioncount() == null ? other.getAttentioncount() == null : this.getAttentioncount().equals(other.getAttentioncount()))
            && (this.getRecommend() == null ? other.getRecommend() == null : this.getRecommend().equals(other.getRecommend()))
            && (this.getEnable() == null ? other.getEnable() == null : this.getEnable().equals(other.getEnable()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGroupid() == null) ? 0 : getGroupid().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getHeadiconurl() == null) ? 0 : getHeadiconurl().hashCode());
        result = prime * result + ((getCreatorid() == null) ? 0 : getCreatorid().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getAttentioncount() == null) ? 0 : getAttentioncount().hashCode());
        result = prime * result + ((getRecommend() == null) ? 0 : getRecommend().hashCode());
        result = prime * result + ((getEnable() == null) ? 0 : getEnable().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupid=").append(groupid);
        sb.append(", title=").append(title);
        sb.append(", type=").append(type);
        sb.append(", description=").append(description);
        sb.append(", headiconurl=").append(headiconurl);
        sb.append(", creatorid=").append(creatorid);
        sb.append(", createtime=").append(createtime);
        sb.append(", attentioncount=").append(attentioncount);
        sb.append(", recommend=").append(recommend);
        sb.append(", enable=").append(enable);
        sb.append("]");
        return sb.toString();
    }
}