package com.yy.ent.tvbar.common.model.domain;

import java.util.Date;

public class HistoryGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_group.userId
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_group.groupId
     *
     * @mbggenerated
     */
    private Integer groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_group.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_group.lastVisitTime
     *
     * @mbggenerated
     */
    private Date lastvisittime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_group.userId
     *
     * @return the value of history_group.userId
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_group.userId
     *
     * @param userid the value for history_group.userId
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_group.groupId
     *
     * @return the value of history_group.groupId
     *
     * @mbggenerated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_group.groupId
     *
     * @param groupid the value for history_group.groupId
     *
     * @mbggenerated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_group.title
     *
     * @return the value of history_group.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_group.title
     *
     * @param title the value for history_group.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_group.lastVisitTime
     *
     * @return the value of history_group.lastVisitTime
     *
     * @mbggenerated
     */
    public Date getLastvisittime() {
        return lastvisittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_group.lastVisitTime
     *
     * @param lastvisittime the value for history_group.lastVisitTime
     *
     * @mbggenerated
     */
    public void setLastvisittime(Date lastvisittime) {
        this.lastvisittime = lastvisittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_group
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        HistoryGroup other = (HistoryGroup) that;
        return (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getGroupid() == null ? other.getGroupid() == null : this.getGroupid().equals(other.getGroupid()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getLastvisittime() == null ? other.getLastvisittime() == null : this.getLastvisittime().equals(other.getLastvisittime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_group
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getGroupid() == null) ? 0 : getGroupid().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getLastvisittime() == null) ? 0 : getLastvisittime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_group
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", groupid=").append(groupid);
        sb.append(", title=").append(title);
        sb.append(", lastvisittime=").append(lastvisittime);
        sb.append("]");
        return sb.toString();
    }
}