package com.yy.ent.tvbar.common.model.domain;

import java.util.Date;

public class Topic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topicId
     *
     * @mbggenerated
     */
    private Integer topicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.souName
     *
     * @mbggenerated
     */
    private String souname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.creatorId
     *
     * @mbggenerated
     */
    private String creatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.replyCount
     *
     * @mbggenerated
     */
    private Integer replycount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.lastReplyTime
     *
     * @mbggenerated
     */
    private Date lastreplytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.eventId
     *
     * @mbggenerated
     */
    private Integer eventid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.enable
     *
     * @mbggenerated
     */
    private Byte enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topicPic
     *
     * @mbggenerated
     */
    private String topicpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.handlePic
     *
     * @mbggenerated
     */
    private String handlepic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topicId
     *
     * @return the value of topic.topicId
     *
     * @mbggenerated
     */
    public Integer getTopicid() {
        return topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topicId
     *
     * @param topicid the value for topic.topicId
     *
     * @mbggenerated
     */
    public void setTopicid(Integer topicid) {
        this.topicid = topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.title
     *
     * @return the value of topic.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.title
     *
     * @param title the value for topic.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.type
     *
     * @return the value of topic.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.type
     *
     * @param type the value for topic.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.description
     *
     * @return the value of topic.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.description
     *
     * @param description the value for topic.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.souName
     *
     * @return the value of topic.souName
     *
     * @mbggenerated
     */
    public String getSouname() {
        return souname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.souName
     *
     * @param souname the value for topic.souName
     *
     * @mbggenerated
     */
    public void setSouname(String souname) {
        this.souname = souname == null ? null : souname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.creatorId
     *
     * @return the value of topic.creatorId
     *
     * @mbggenerated
     */
    public String getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.creatorId
     *
     * @param creatorid the value for topic.creatorId
     *
     * @mbggenerated
     */
    public void setCreatorid(String creatorid) {
        this.creatorid = creatorid == null ? null : creatorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.createTime
     *
     * @return the value of topic.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.createTime
     *
     * @param createtime the value for topic.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.replyCount
     *
     * @return the value of topic.replyCount
     *
     * @mbggenerated
     */
    public Integer getReplycount() {
        return replycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.replyCount
     *
     * @param replycount the value for topic.replyCount
     *
     * @mbggenerated
     */
    public void setReplycount(Integer replycount) {
        this.replycount = replycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.lastReplyTime
     *
     * @return the value of topic.lastReplyTime
     *
     * @mbggenerated
     */
    public Date getLastreplytime() {
        return lastreplytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.lastReplyTime
     *
     * @param lastreplytime the value for topic.lastReplyTime
     *
     * @mbggenerated
     */
    public void setLastreplytime(Date lastreplytime) {
        this.lastreplytime = lastreplytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.eventId
     *
     * @return the value of topic.eventId
     *
     * @mbggenerated
     */
    public Integer getEventid() {
        return eventid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.eventId
     *
     * @param eventid the value for topic.eventId
     *
     * @mbggenerated
     */
    public void setEventid(Integer eventid) {
        this.eventid = eventid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.enable
     *
     * @return the value of topic.enable
     *
     * @mbggenerated
     */
    public Byte getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.enable
     *
     * @param enable the value for topic.enable
     *
     * @mbggenerated
     */
    public void setEnable(Byte enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topicPic
     *
     * @return the value of topic.topicPic
     *
     * @mbggenerated
     */
    public String getTopicpic() {
        return topicpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topicPic
     *
     * @param topicpic the value for topic.topicPic
     *
     * @mbggenerated
     */
    public void setTopicpic(String topicpic) {
        this.topicpic = topicpic == null ? null : topicpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.handlePic
     *
     * @return the value of topic.handlePic
     *
     * @mbggenerated
     */
    public String getHandlepic() {
        return handlepic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.handlePic
     *
     * @param handlepic the value for topic.handlePic
     *
     * @mbggenerated
     */
    public void setHandlepic(String handlepic) {
        this.handlepic = handlepic == null ? null : handlepic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Topic other = (Topic) that;
        return (this.getTopicid() == null ? other.getTopicid() == null : this.getTopicid().equals(other.getTopicid()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getSouname() == null ? other.getSouname() == null : this.getSouname().equals(other.getSouname()))
            && (this.getCreatorid() == null ? other.getCreatorid() == null : this.getCreatorid().equals(other.getCreatorid()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getReplycount() == null ? other.getReplycount() == null : this.getReplycount().equals(other.getReplycount()))
            && (this.getLastreplytime() == null ? other.getLastreplytime() == null : this.getLastreplytime().equals(other.getLastreplytime()))
            && (this.getEventid() == null ? other.getEventid() == null : this.getEventid().equals(other.getEventid()))
            && (this.getEnable() == null ? other.getEnable() == null : this.getEnable().equals(other.getEnable()))
            && (this.getTopicpic() == null ? other.getTopicpic() == null : this.getTopicpic().equals(other.getTopicpic()))
            && (this.getHandlepic() == null ? other.getHandlepic() == null : this.getHandlepic().equals(other.getHandlepic()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTopicid() == null) ? 0 : getTopicid().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getSouname() == null) ? 0 : getSouname().hashCode());
        result = prime * result + ((getCreatorid() == null) ? 0 : getCreatorid().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getReplycount() == null) ? 0 : getReplycount().hashCode());
        result = prime * result + ((getLastreplytime() == null) ? 0 : getLastreplytime().hashCode());
        result = prime * result + ((getEventid() == null) ? 0 : getEventid().hashCode());
        result = prime * result + ((getEnable() == null) ? 0 : getEnable().hashCode());
        result = prime * result + ((getTopicpic() == null) ? 0 : getTopicpic().hashCode());
        result = prime * result + ((getHandlepic() == null) ? 0 : getHandlepic().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", topicid=").append(topicid);
        sb.append(", title=").append(title);
        sb.append(", type=").append(type);
        sb.append(", description=").append(description);
        sb.append(", souname=").append(souname);
        sb.append(", creatorid=").append(creatorid);
        sb.append(", createtime=").append(createtime);
        sb.append(", replycount=").append(replycount);
        sb.append(", lastreplytime=").append(lastreplytime);
        sb.append(", eventid=").append(eventid);
        sb.append(", enable=").append(enable);
        sb.append(", topicpic=").append(topicpic);
        sb.append(", handlepic=").append(handlepic);
        sb.append("]");
        return sb.toString();
    }
}