package com.yy.ent.tvbar.common.model.domain;

import java.util.Date;

public class ViewPoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_point.pointId
     *
     * @mbggenerated
     */
    private Integer pointid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_point.replyId
     *
     * @mbggenerated
     */
    private Integer replyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_point.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_point.topicId
     *
     * @mbggenerated
     */
    private Integer topicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_point.creatorId
     *
     * @mbggenerated
     */
    private String creatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_point.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_point.enable
     *
     * @mbggenerated
     */
    private Byte enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_point.viewPic
     *
     * @mbggenerated
     */
    private String viewpic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_point.pointId
     *
     * @return the value of view_point.pointId
     *
     * @mbggenerated
     */
    public Integer getPointid() {
        return pointid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_point.pointId
     *
     * @param pointid the value for view_point.pointId
     *
     * @mbggenerated
     */
    public void setPointid(Integer pointid) {
        this.pointid = pointid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_point.replyId
     *
     * @return the value of view_point.replyId
     *
     * @mbggenerated
     */
    public Integer getReplyid() {
        return replyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_point.replyId
     *
     * @param replyid the value for view_point.replyId
     *
     * @mbggenerated
     */
    public void setReplyid(Integer replyid) {
        this.replyid = replyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_point.description
     *
     * @return the value of view_point.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_point.description
     *
     * @param description the value for view_point.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_point.topicId
     *
     * @return the value of view_point.topicId
     *
     * @mbggenerated
     */
    public Integer getTopicid() {
        return topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_point.topicId
     *
     * @param topicid the value for view_point.topicId
     *
     * @mbggenerated
     */
    public void setTopicid(Integer topicid) {
        this.topicid = topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_point.creatorId
     *
     * @return the value of view_point.creatorId
     *
     * @mbggenerated
     */
    public String getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_point.creatorId
     *
     * @param creatorid the value for view_point.creatorId
     *
     * @mbggenerated
     */
    public void setCreatorid(String creatorid) {
        this.creatorid = creatorid == null ? null : creatorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_point.createTime
     *
     * @return the value of view_point.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_point.createTime
     *
     * @param createtime the value for view_point.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_point.enable
     *
     * @return the value of view_point.enable
     *
     * @mbggenerated
     */
    public Byte getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_point.enable
     *
     * @param enable the value for view_point.enable
     *
     * @mbggenerated
     */
    public void setEnable(Byte enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_point.viewPic
     *
     * @return the value of view_point.viewPic
     *
     * @mbggenerated
     */
    public String getViewpic() {
        return viewpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_point.viewPic
     *
     * @param viewpic the value for view_point.viewPic
     *
     * @mbggenerated
     */
    public void setViewpic(String viewpic) {
        this.viewpic = viewpic == null ? null : viewpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_point
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ViewPoint other = (ViewPoint) that;
        return (this.getPointid() == null ? other.getPointid() == null : this.getPointid().equals(other.getPointid()))
            && (this.getReplyid() == null ? other.getReplyid() == null : this.getReplyid().equals(other.getReplyid()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getTopicid() == null ? other.getTopicid() == null : this.getTopicid().equals(other.getTopicid()))
            && (this.getCreatorid() == null ? other.getCreatorid() == null : this.getCreatorid().equals(other.getCreatorid()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getEnable() == null ? other.getEnable() == null : this.getEnable().equals(other.getEnable()))
            && (this.getViewpic() == null ? other.getViewpic() == null : this.getViewpic().equals(other.getViewpic()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_point
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPointid() == null) ? 0 : getPointid().hashCode());
        result = prime * result + ((getReplyid() == null) ? 0 : getReplyid().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getTopicid() == null) ? 0 : getTopicid().hashCode());
        result = prime * result + ((getCreatorid() == null) ? 0 : getCreatorid().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getEnable() == null) ? 0 : getEnable().hashCode());
        result = prime * result + ((getViewpic() == null) ? 0 : getViewpic().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_point
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pointid=").append(pointid);
        sb.append(", replyid=").append(replyid);
        sb.append(", description=").append(description);
        sb.append(", topicid=").append(topicid);
        sb.append(", creatorid=").append(creatorid);
        sb.append(", createtime=").append(createtime);
        sb.append(", enable=").append(enable);
        sb.append(", viewpic=").append(viewpic);
        sb.append("]");
        return sb.toString();
    }
}